---
- name: Find and prepare the virtual machine images
  hosts: image-server
  vars_files:
    - vars/openstack.yml
  pre_tasks:
    - name: Ensure the local artifacts directory exists
      file:
        path: "{{ artifacts_directory }}"
        state: directory
      delegate_to: localhost
  roles:
    - { role: image_preparation, when: openstack_upload_images | default(True) | bool }

- name: Upload images to OpenStack
  hosts: openstack-server
  vars_files:
    - vars/openstack.yml
  roles:
    - { role: openstack_upload_images, when: openstack_upload_images | default(True) | bool }

- name: Set up one virtual machine server in a new OpenStack environment
  hosts: openstack-server
  vars_files:
    - vars/openstack.yml
  roles:
    - openstack_create_server

- name: Install the prerequisite software on the virtual machine server
  hosts: target-server
  # This host may not have Python installed, do not collect facts at this time.
  gather_facts: false
  roles:
    - openshift_dependencies

- name: Install OpenShift on OpenStack
  hosts: target-server
  vars_files:
    - vars/openstack.yml
    - vars/openshift.yml
  roles:
    - pbench_storage
    - openshift_dns
    - openshift_on_openstack
    - role: openshift_metering
      when: openshift_metering_install|bool

- name: Find the core cluster and add it to the in-memory inventory
  hosts: openstack-server
  vars_files:
    - vars/openstack.yml
  roles:
    - openstack_add_fips
    - openshift_get_core_cluster
    - openstack_etc_hosts

- name: Use the remaining disk space on the core cluster for Pbench
  hosts: masters infras lb cns app_nodes
  vars_files:
    - vars/openstack.yml
  roles:
    - pbench_storage

- name: Run post OpenShift installation tasks
  hosts: target-server
  vars_files:
    - vars/openstack.yml
  roles:
    - openshift_copy_kube_config
    - openstack_etc_hosts
    - openshift_label_nodes
    - pbench_web_server
    - openshift_move_results

- name: Copy the certs to the location where golang looks for
  hosts: masters
  become: yes
  roles:
    - openshift_copy_certs
