---
# A string path relative to the user's home directory to the atomic image.
atomic_image: "{{ lookup('env', 'atomic_image') }}"
# Should the qcow2 images be removed in order to save space?
delete_qcow2_images: false
# A string path relative to the user's home directory.
image_directory: image_builder/qcow_images
# Copy the images to this remote host.
remote_host: "{{ groups['openstack-server'][0] }}"
# Copy the images to this directory on the remote host.
remote_image_directory: "/home/{{ hostvars[remote_host]['ansible_user'] }}/scale-ci"
# A string path relative to the user's home directory to the rhel image.
rhel_image: "{{ lookup('env', 'rhel_image') }}"
# The root directory of the Apache httpd server.
web_root: /var/www/html
