---
# A list of regular expressions to search and replace in openshift-ansible all.yml.
all_yml:
  - { find: "^openshift_openstack_clusterid.*", replace: "openshift_openstack_clusterid: \"{{ openshift_env_id }}\"" }
  - { find: "^openshift_openstack_dns_nameservers:.*", replace: "openshift_openstack_dns_nameservers:s: [{{ public_dns_nameservers }}]" }
  - { find: "^openshift_openstack_keypair_name.*", replace: "openshift_openstack_keypair_name: \"{{ openstack_keypair_name }}\"" }
  - { find: "^openshift_openstack_external_network_name.*", replace: "openshift_openstack_external_network_name: \"{{ openstack_public_network_name }}\"" }
  - { find: "^openshift_openstack_default_image_name.*", replace: "openshift_openstack_default_image_name: \"{{ default_image_name }}\"" }
  - { find: "^openshift_openstack_num_masters.*", replace: "openshift_openstack_num_masters: 3" }
  - { find: "^openshift_openstack_num_infra.*", replace: "openshift_openstack_num_infra: 3" }
  - { find: "^#openshift_openstack_master_flavor:.*", replace: "openshift_openstack_master_flavor:: \"master_etcd\"" }
  - { find: "^#openshift_openstack_infra_flavor:.*", replace: "openshift_openstack_infra_flavor:: \"infra_elastic\"" }
  - { find: "^#openshift_openstack_node_flavor.*", replace: "openshift_openstack_node_flavor: \"node_average\"" }
  - { find: "^#openshift_openstack_lb_flavor:.*", replace: "openshift_openstack_lb_flavor:: \"load_balancer\"" }
  - { find: "^openshift_openstack_default_flavor:.*", replace: "openshift_openstack_default_flavor:: \"m1.medium\"" }
  # - { find: "^#manage_packages.*", replace: "manage_packages: false"}
  # Do not use Cinder volumes. TODO: Remove this once Cinder is working.
  # - { find: "^#ephemeral_volumes.*", replace: "ephemeral_volumes: true"}
# The OpenStack image name to use in the templates.
default_image_name: "{{ lookup('env', 'default_image_name')|default('ocp-3.7-rhel', true) }}"
# The path to the OpenStack RC file on the server vm, may be named differently than other servers.
openstack_rc: "{{ lookup('env', 'openstack_rc_path')|default(ansible_user_dir ~ '/keystonerc', true) }}"
# A list of regular expressions to search and replace in the openshift-ansible OSEv3.yml.
osev3_yml:
  - { find: "^openshift_deployment_type: origin", replace: "#openshift_deployment_type: origin" }
  - { find: "^#openshift_deployment_type: openshift-enterprise", replace: "openshift_deployment_type: openshift-enterprise" }
# Look for a space separated string of time servers from an environment variable.
time_servers: "{{ lookup('env', 'time_servers')|default('0.pool.ntp.org 1.pool.ntp.org 2.pool.ntp.org 3.pool.ntp.org', true) }}"
# Break up the space separated string into a list of time servers.
time_servers_list: "{{ time_servers.split(' ') }}"
